# Since I want to test Python and C++, need to use a Linux container
# Local debug line: docker run -it --volume=/Users/sseritan/Documents/Research/MartinezGroup/tcpb-client:/tcpb-client --workdir="/tcpb-client" sseritan/tcpb-client-docker
image: sseritan/tcpb-client-docker

pipelines:
  default:
    - step:
        script:
          # Generate protobuf
          - cd proto/
          - protoc terachem_server.proto --python_out=../tcpb
          - cd ../
          # Test Python with tox
          - tox
